### PR TITLE
fix typo in README.md

### PR DESCRIPTION
**Pull request by mhujer**

### CODE REVIEW

**Comment by mcfedr** [comment]
ha, thats a typo in the bundle name

**Comment by mcfedr** [comment]
Fixed this in 3.0.2, by correctly renaming the bundle

**Comment by mhujer** [comment]
@mcfedr 👍 

I think it should have been another major release as anyone using `~3.0` (or even `~3.0.0`) would experience a broken app after the update. But nevermind :-)

**Comment by mcfedr** [comment]
Agree, I normally would but its such a small and annoying thing, hopefully wont be too annoying :)

**Pull request closed without merging**
